version: "3.3"
services:
  app:
    image: golang-compile-daemon:1.17-alpine
    environment:
      PORT: 5000
      REDIS_URL: redis:6379
    ports:
      - 4060:5000
      - 2345:2345
    volumes:
      - ./:/app
      - pkg-cd-go:/go/pkg/mod
    command: CompileDaemon -color=true -build "echo restarting..." -command "sh ./_scripts/run-dlv.sh"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - "6479:6379"
    volumes:
      - ./data/conf:/usr/local/etc/redis
      - ./data/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  pkg-cd-go: