version: "3.3"
services:
  app:
    image: golang-compile-daemon:1.17-alpine
    environment:
      PORT: 5000
      #REDIS_URL: redis://redis
      #PG_URL: postgres://
    ports:
      - 4060:5000
      - 2345:2345
    volumes:
      - ./:/app
      - pkg-cd-go:/go/pkg/mod
    command: CompileDaemon -color=true -build "echo restarting..." -command "sh ./_scripts/run-dlv.sh"

    #depends_on:
volumes:
  pkg-cd-go: