version: "3.3"
services:
  app:
    image: node:16.5-buster
    environment:
      PORT: 3000
      MONGO_URL: mongodb://mongo:27017/docker4dev 
    ports:
      - 4050:3000
      - 9229:9229
      - 9239:9239 # other debug. node --inspect-brk=0.0.0.0:9239 script.js
    volumes:
      - ./:/app
      - nm-cd-node:/app/node_modules
    command: sh -c "cd app && npm i && npx nodemon --inspect=0.0.0.0:9229 --ext js,json,env,gql server.js"
    #depends_on:
  mongo:
    image: mongo:4.2.11
    ports:
      - "27020:27017"
    volumes:
      - ./data/mongo:/data/db
    command: --nojournal

volumes:
  nm-cd-node: